import { DatePipe } from '@angular/common';
import { Component, EventEmitter, HostListener, Input, OnDestroy, OnInit, Output, computed, signal } from '@angular/core';
import { isRawFileName } from '../raw-format';

export interface MediaViewerItem {
  fileId: number;
  mediaType: 'image' | 'video';
  // Optional: only displays what is actually available (see issue #22) — a media item not
  // yet processed by the EXIF/geo jobs has neither dateTaken nor location, a media item with
  // no known name (hypothetical case) also doesn't show the RAW badge.
  name?: string | null;
  dateTaken?: string | null;
  country?: string | null;
  region?: string | null;
  city?: string | null;
}

const SWIPE_THRESHOLD_PX = 50;

// Generalized full-screen viewer (image + video, next/previous navigation) —
// replaces VideoPopupComponent (video only). Reused by Gallery and Album Detail.
@Component({
  selector: 'app-media-viewer',
  standalone: true,
  imports: [DatePipe],
  templateUrl: './media-viewer.component.html',
  styleUrl: './media-viewer.component.scss',
})
export class MediaViewerComponent implements OnInit, OnDestroy {
  @Input({ required: true }) items!: MediaViewerItem[];
  @Input({ required: true }) startIndex!: number;
  // Video thumbnail (poster) — small size, same as in the grid.
  @Input({ required: true }) posterUrl!: (fileId: number) => string;
  // Full-screen display of an image: a large, uncropped thumbnail generated by
  // pCloud, not the raw file — RAW formats (e.g. .CR2) are not decodable by
  // an <img>, and pCloud can return an error on the direct link for these files.
  @Input({ required: true }) imageUrl!: (fileId: number) => string;
  @Input({ required: true }) streamUrl!: (fileId: number) => string;
  @Input({ required: true }) downloadUrl!: (fileId: number) => string;
  @Output() closed = new EventEmitter<void>();

  protected readonly index = signal(0);
  protected readonly current = computed(() => this.items[this.index()]);
  protected readonly hasPrevious = computed(() => this.index() > 0);
  protected readonly hasNext = computed(() => this.index() < this.items.length - 1);
  protected readonly isRaw = computed(() => isRawFileName(this.current()?.name));
  // "city, region, country" string keeping only the segments that are actually known — see issue #22.
  protected readonly locationLabel = computed(() => {
    const item = this.current();
    const parts = [item?.city, item?.region, item?.country].filter((p): p is string => !!p);
    return parts.length > 0 ? parts.join(', ') : null;
  });

  private touchStartX: number | null = null;
  private previousBodyOverflow = '';

  ngOnInit(): void {
    this.index.set(this.startIndex);
    // The overlay is `position: fixed` but that's not enough to prevent the underlying page
    // from scrolling (especially on mobile) — see issue #2.
    this.previousBodyOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
  }

  ngOnDestroy(): void {
    document.body.style.overflow = this.previousBodyOverflow;
  }

  @HostListener('window:keydown', ['$event'])
  onKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      this.closed.emit();
    } else if (event.key === 'ArrowLeft') {
      this.previous();
    } else if (event.key === 'ArrowRight') {
      this.next();
    }
  }

  previous(): void {
    if (this.hasPrevious()) {
      this.index.update((i) => i - 1);
    }
  }

  next(): void {
    if (this.hasNext()) {
      this.index.update((i) => i + 1);
    }
  }

  onTouchStart(event: TouchEvent): void {
    this.touchStartX = event.touches[0]?.clientX ?? null;
  }

  onTouchEnd(event: TouchEvent): void {
    if (this.touchStartX === null) {
      return;
    }

    const endX = event.changedTouches[0]?.clientX ?? this.touchStartX;
    const delta = endX - this.touchStartX;
    this.touchStartX = null;

    if (delta > SWIPE_THRESHOLD_PX) {
      this.previous();
    } else if (delta < -SWIPE_THRESHOLD_PX) {
      this.next();
    }
  }
}
